import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Employee } from './employee.entity';

export interface PaginationResult<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

@Injectable()
export class EmployeesService {
  constructor(
    @InjectRepository(Employee)
    private readonly employeeRepository: Repository<Employee>,
  ) {}

  async findAll(page: number = 1, limit: number = 10): Promise<PaginationResult<Employee>> {
    const skip = (page - 1) * limit;
    
    const [data, total] = await this.employeeRepository.findAndCount({
      skip,
      take: limit,
      order: { createdAt: 'DESC' },
    });

    return {
      data,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: number): Promise<Employee> {
    return this.employeeRepository.findOne({ where: { id } });
  }

  async create(employeeData: Partial<Employee>): Promise<Employee> {
    const employee = this.employeeRepository.create({
      ...employeeData,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    return this.employeeRepository.save(employee);
  }

  async update(id: number, employeeData: Partial<Employee>): Promise<Employee> {
    await this.employeeRepository.update(id, {
      ...employeeData,
      updatedAt: new Date(),
    });
    return this.employeeRepository.findOne({ where: { id } });
  }

  async remove(id: number): Promise<void> {
    await this.employeeRepository.delete(id);
  }

  async search(query: string, page: number = 1, limit: number = 10): Promise<PaginationResult<Employee>> {
    const skip = (page - 1) * limit;
    
    const [data, total] = await this.employeeRepository
      .createQueryBuilder('employee')
      .where('employee.name ILIKE :query OR employee.candidateName ILIKE :query OR employee.position ILIKE :query OR employee.jobRole ILIKE :query OR employee.candidateId ILIKE :query', {
        query: `%${query}%`,
      })
      .skip(skip)
      .take(limit)
      .orderBy('employee.createdAt', 'DESC')
      .getManyAndCount();

    return {
      data,
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async seedDefaultEmployees(): Promise<void> {
    const defaultEmployees = [
      {
        name: 'Kevin White',
        candidateName: 'Kevin White',
        candidateAddress: '852 Security St, Chicago, USA',
        position: 'Security Engineer',
        jobRole: 'Cybersecurity Specialist',
        salary: '88000',
        basicSalary: '63000',
        basicMonthly: '5250',
        hra: '12600',
        hraMonthly: '1050',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5300',
        lta: '10600',
        otherBenefits: '2300',
        otherMonthly: '192',
        totalSalary: '88000',
        totalMonthly: '7333',
        joiningDate: '2023-09-01',
        offerExpiryDate: '2023-08-15',
        currentDate: '2023-08-01',
        year: '2023',
        candidateId: 'EMP006',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Karen Rodriguez',
        workLocation: 'Chicago',
        isActive: true,
      },
      {
        name: 'Michelle Garcia',
        candidateName: 'Michelle Garcia',
        candidateAddress: '963 AI Drive, Seattle, USA',
        position: 'AI Engineer',
        jobRole: 'Machine Learning Engineer',
        salary: '95000',
        basicSalary: '68000',
        basicMonthly: '5667',
        hra: '13600',
        hraMonthly: '1133',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '6000',
        lta: '12000',
        otherBenefits: '2800',
        otherMonthly: '233',
        totalSalary: '95000',
        totalMonthly: '7917',
        joiningDate: '2023-10-10',
        offerExpiryDate: '2023-09-25',
        currentDate: '2023-09-01',
        year: '2023',
        candidateId: 'EMP007',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Larry Kim',
        workLocation: 'Seattle',
        isActive: true,
      },
      {
        name: 'Brian Lee',
        candidateName: 'Brian Lee',
        candidateAddress: '159 Cloud Way, Austin, USA',
        position: 'Cloud Architect',
        jobRole: 'Cloud Solutions Architect',
        salary: '100000',
        basicSalary: '72000',
        basicMonthly: '6000',
        hra: '14400',
        hraMonthly: '1200',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '6500',
        lta: '13000',
        otherBenefits: '3200',
        otherMonthly: '267',
        totalSalary: '100000',
        totalMonthly: '8333',
        joiningDate: '2023-11-01',
        offerExpiryDate: '2023-10-15',
        currentDate: '2023-10-01',
        year: '2023',
        candidateId: 'EMP008',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Nancy Patel',
        workLocation: 'Austin',
        isActive: true,
      },
      {
        name: 'Amanda Harris',
        candidateName: 'Amanda Harris',
        candidateAddress: '357 Analytics Blvd, Boston, USA',
        position: 'Business Analyst',
        jobRole: 'Data Business Analyst',
        salary: '76000',
        basicSalary: '55000',
        basicMonthly: '4583',
        hra: '11000',
        hraMonthly: '917',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4100',
        lta: '8200',
        otherBenefits: '1500',
        otherMonthly: '125',
        totalSalary: '76000',
        totalMonthly: '6333',
        joiningDate: '2023-12-05',
        offerExpiryDate: '2023-11-20',
        currentDate: '2023-11-01',
        year: '2023',
        candidateId: 'EMP009',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Oscar Nguyen',
        workLocation: 'Boston',
        isActive: true,
      },
      {
        name: 'Daniel Clark',
        candidateName: 'Daniel Clark',
        candidateAddress: '468 Support St, San Francisco, USA',
        position: 'Technical Support',
        jobRole: 'Customer Support Engineer',
        salary: '65000',
        basicSalary: '47000',
        basicMonthly: '3917',
        hra: '9400',
        hraMonthly: '783',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3200',
        lta: '6400',
        otherBenefits: '1000',
        otherMonthly: '83',
        totalSalary: '65000',
        totalMonthly: '5417',
        joiningDate: '2024-01-15',
        offerExpiryDate: '2023-12-31',
        currentDate: '2023-12-01',
        year: '2024',
        candidateId: 'EMP010',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Paula Ramirez',
        workLocation: 'San Francisco',
        isActive: true,
      },
      {
        name: 'Rachel Lewis',
        candidateName: 'Rachel Lewis',
        candidateAddress: '579 Project Ave, New York, USA',
        position: 'Project Manager',
        jobRole: 'Agile Project Manager',
        salary: '85000',
        basicSalary: '61000',
        basicMonthly: '5083',
        hra: '12200',
        hraMonthly: '1017',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5100',
        lta: '10200',
        otherBenefits: '2100',
        otherMonthly: '175',
        totalSalary: '85000',
        totalMonthly: '7083',
        joiningDate: '2024-02-01',
        offerExpiryDate: '2024-01-15',
        currentDate: '2024-01-01',
        year: '2024',
        candidateId: 'EMP011',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Quinn Stewart',
        workLocation: 'New York',
        isActive: true,
      },
      {
        name: 'Steven Walker',
        candidateName: 'Steven Walker',
        candidateAddress: '680 Design Blvd, Los Angeles, USA',
        position: 'Graphic Designer',
        jobRole: 'Visual Designer',
        salary: '70000',
        basicSalary: '50000',
        basicMonthly: '4167',
        hra: '10000',
        hraMonthly: '833',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3500',
        lta: '7000',
        otherBenefits: '1200',
        otherMonthly: '100',
        totalSalary: '70000',
        totalMonthly: '5833',
        joiningDate: '2024-03-10',
        offerExpiryDate: '2024-02-20',
        currentDate: '2024-02-01',
        year: '2024',
        candidateId: 'EMP012',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Rachel Turner',
        workLocation: 'Los Angeles',
        isActive: true,
      },
      {
        name: 'Olivia Hall',
        candidateName: 'Olivia Hall',
        candidateAddress: '791 Content St, Chicago, USA',
        position: 'Content Writer',
        jobRole: 'Technical Writer',
        salary: '65000',
        basicSalary: '47000',
        basicMonthly: '3917',
        hra: '9400',
        hraMonthly: '783',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3200',
        lta: '6400',
        otherBenefits: '1000',
        otherMonthly: '83',
        totalSalary: '65000',
        totalMonthly: '5417',
        joiningDate: '2024-04-05',
        offerExpiryDate: '2024-03-20',
        currentDate: '2024-03-01',
        year: '2024',
        candidateId: 'EMP013',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Sam Underwood',
        workLocation: 'Chicago',
        isActive: true,
      },
      {
        name: 'Tyler Young',
        candidateName: 'Tyler Young',
        candidateAddress: '802 Research Way, Seattle, USA',
        position: 'Research Scientist',
        jobRole: 'AI Research Scientist',
        salary: '110000',
        basicSalary: '79000',
        basicMonthly: '6583',
        hra: '15800',
        hraMonthly: '1317',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '7200',
        lta: '14400',
        otherBenefits: '3800',
        otherMonthly: '317',
        totalSalary: '110000',
        totalMonthly: '9167',
        joiningDate: '2024-05-15',
        offerExpiryDate: '2024-04-30',
        currentDate: '2024-04-01',
        year: '2024',
        candidateId: 'EMP014',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Tina Vargas',
        workLocation: 'Seattle',
        isActive: true,
      },
      {
        name: 'Sophia King',
        candidateName: 'Sophia King',
        candidateAddress: '913 Strategy Ave, Austin, USA',
        position: 'Strategy Consultant',
        jobRole: 'Business Strategy Consultant',
        salary: '95000',
        basicSalary: '68000',
        basicMonthly: '5667',
        hra: '13600',
        hraMonthly: '1133',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '6000',
        lta: '12000',
        otherBenefits: '2800',
        otherMonthly: '233',
        totalSalary: '95000',
        totalMonthly: '7917',
        joiningDate: '2024-06-01',
        offerExpiryDate: '2024-05-15',
        currentDate: '2024-05-01',
        year: '2024',
        candidateId: 'EMP015',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Ulysses Wright',
        workLocation: 'Austin',
        isActive: true,
      },
      {
        name: 'Nathan Scott',
        candidateName: 'Nathan Scott',
        candidateAddress: '024 Training Blvd, Boston, USA',
        position: 'Training Coordinator',
        jobRole: 'Employee Training Specialist',
        salary: '68000',
        basicSalary: '49000',
        basicMonthly: '4083',
        hra: '9800',
        hraMonthly: '817',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3400',
        lta: '6800',
        otherBenefits: '1100',
        otherMonthly: '92',
        totalSalary: '68000',
        totalMonthly: '5667',
        joiningDate: '2024-07-10',
        offerExpiryDate: '2024-06-25',
        currentDate: '2024-06-01',
        year: '2024',
        candidateId: 'EMP016',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Victoria Xu',
        workLocation: 'Boston',
        isActive: true,
      },
      {
        name: 'Isabella Green',
        candidateName: 'Isabella Green',
        candidateAddress: '135 Compliance St, San Francisco, USA',
        position: 'Compliance Officer',
        jobRole: 'Regulatory Compliance Specialist',
        salary: '78000',
        basicSalary: '56000',
        basicMonthly: '4667',
        hra: '11200',
        hraMonthly: '933',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4200',
        lta: '8400',
        otherBenefits: '1600',
        otherMonthly: '133',
        totalSalary: '78000',
        totalMonthly: '6500',
        joiningDate: '2024-08-05',
        offerExpiryDate: '2024-07-20',
        currentDate: '2024-07-01',
        year: '2024',
        candidateId: 'EMP017',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'William Young',
        workLocation: 'San Francisco',
        isActive: true,
      },
      {
        name: 'Ethan Baker',
        candidateName: 'Ethan Baker',
        candidateAddress: '246 Finance Ave, New York, USA',
        position: 'Financial Analyst',
        jobRole: 'Corporate Finance Analyst',
        salary: '82000',
        basicSalary: '59000',
        basicMonthly: '4917',
        hra: '11800',
        hraMonthly: '983',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4600',
        lta: '9200',
        otherBenefits: '1900',
        otherMonthly: '158',
        totalSalary: '82000',
        totalMonthly: '6833',
        joiningDate: '2024-09-15',
        offerExpiryDate: '2024-08-31',
        currentDate: '2024-08-01',
        year: '2024',
        candidateId: 'EMP018',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Xander Zhao',
        workLocation: 'New York',
        isActive: true,
      },
      {
        name: 'Ava Nelson',
        candidateName: 'Ava Nelson',
        candidateAddress: '357 Legal Blvd, Los Angeles, USA',
        position: 'Legal Counsel',
        jobRole: 'Corporate Lawyer',
        salary: '120000',
        basicSalary: '86000',
        basicMonthly: '7167',
        hra: '17200',
        hraMonthly: '1433',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '8000',
        lta: '16000',
        otherBenefits: '4400',
        otherMonthly: '367',
        totalSalary: '120000',
        totalMonthly: '10000',
        joiningDate: '2024-10-01',
        offerExpiryDate: '2024-09-15',
        currentDate: '2024-09-01',
        year: '2024',
        candidateId: 'EMP019',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Yara Kumar',
        workLocation: 'Los Angeles',
        isActive: true,
      },
      {
        name: 'Mason Carter',
        candidateName: 'Mason Carter',
        candidateAddress: '468 Sales St, Chicago, USA',
        position: 'Sales Manager',
        jobRole: 'Enterprise Sales Manager',
        salary: '90000',
        basicSalary: '65000',
        basicMonthly: '5417',
        hra: '13000',
        hraMonthly: '1083',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5500',
        lta: '11000',
        otherBenefits: '2500',
        otherMonthly: '208',
        totalSalary: '90000',
        totalMonthly: '7500',
        joiningDate: '2024-11-10',
        offerExpiryDate: '2024-10-25',
        currentDate: '2024-10-01',
        year: '2024',
        candidateId: 'EMP020',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Zoe Liu',
        workLocation: 'Chicago',
        isActive: true,
      },
      {
        name: 'Harper Mitchell',
        candidateName: 'Harper Mitchell',
        candidateAddress: '579 Operations Way, Seattle, USA',
        position: 'Operations Manager',
        jobRole: 'Business Operations Manager',
        salary: '85000',
        basicSalary: '61000',
        basicMonthly: '5083',
        hra: '12200',
        hraMonthly: '1017',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5100',
        lta: '10200',
        otherBenefits: '2100',
        otherMonthly: '175',
        totalSalary: '85000',
        totalMonthly: '7083',
        joiningDate: '2024-12-01',
        offerExpiryDate: '2024-11-15',
        currentDate: '2024-11-01',
        year: '2024',
        candidateId: 'EMP021',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Aaron Brooks',
        workLocation: 'Seattle',
        isActive: true,
      },
      {
        name: 'Evelyn Perez',
        candidateName: 'Evelyn Perez',
        candidateAddress: '680 HR Ave, Austin, USA',
        position: 'HR Specialist',
        jobRole: 'Human Resources Specialist',
        salary: '72000',
        basicSalary: '52000',
        basicMonthly: '4333',
        hra: '10400',
        hraMonthly: '867',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3700',
        lta: '7400',
        otherBenefits: '1300',
        otherMonthly: '108',
        totalSalary: '72000',
        totalMonthly: '6000',
        joiningDate: '2025-01-15',
        offerExpiryDate: '2024-12-31',
        currentDate: '2024-12-01',
        year: '2025',
        candidateId: 'EMP022',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Bella Chen',
        workLocation: 'Austin',
        isActive: true,
      },
      {
        name: 'Logan Roberts',
        candidateName: 'Logan Roberts',
        candidateAddress: '791 Logistics Blvd, Boston, USA',
        position: 'Logistics Coordinator',
        jobRole: 'Supply Chain Coordinator',
        salary: '65000',
        basicSalary: '47000',
        basicMonthly: '3917',
        hra: '9400',
        hraMonthly: '783',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3200',
        lta: '6400',
        otherBenefits: '1000',
        otherMonthly: '83',
        totalSalary: '65000',
        totalMonthly: '5417',
        joiningDate: '2025-02-01',
        offerExpiryDate: '2025-01-15',
        currentDate: '2025-01-01',
        year: '2025',
        candidateId: 'EMP023',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Caleb Davis',
        workLocation: 'Boston',
        isActive: true,
      },
      {
        name: 'Abigail Turner',
        candidateName: 'Abigail Turner',
        candidateAddress: '802 Quality St, San Francisco, USA',
        position: 'Quality Assurance',
        jobRole: 'QA Lead',
        salary: '78000',
        basicSalary: '56000',
        basicMonthly: '4667',
        hra: '11200',
        hraMonthly: '933',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4200',
        lta: '8400',
        otherBenefits: '1600',
        otherMonthly: '133',
        totalSalary: '78000',
        totalMonthly: '6500',
        joiningDate: '2025-03-10',
        offerExpiryDate: '2025-02-20',
        currentDate: '2025-02-01',
        year: '2025',
        candidateId: 'EMP024',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Diana Evans',
        workLocation: 'San Francisco',
        isActive: true,
      },
      {
        name: 'Jackson Collins',
        candidateName: 'Jackson Collins',
        candidateAddress: '913 Executive Ave, New York, USA',
        position: 'Executive Assistant',
        jobRole: 'C-Suite Assistant',
        salary: '70000',
        basicSalary: '50000',
        basicMonthly: '4167',
        hra: '10000',
        hraMonthly: '833',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3500',
        lta: '7000',
        otherBenefits: '1200',
        otherMonthly: '100',
        totalSalary: '70000',
        totalMonthly: '5833',
        joiningDate: '2025-04-05',
        offerExpiryDate: '2025-03-20',
        currentDate: '2025-03-01',
        year: '2025',
        candidateId: 'EMP025',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Ethan Foster',
        workLocation: 'New York',
        isActive: true,
      },
      {
        name: 'Emily Davis',
        candidateName: 'Emily Davis',
        candidateAddress: '987 Innovation Way, Austin, USA',
        position: 'Data Scientist',
        jobRole: 'Data Analyst',
        salary: '90000',
        basicSalary: '65000',
        basicMonthly: '5417',
        hra: '13000',
        hraMonthly: '1083',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5500',
        lta: '11000',
        otherBenefits: '2500',
        otherMonthly: '208',
        totalSalary: '90000',
        totalMonthly: '7500',
        joiningDate: '2023-04-15',
        offerExpiryDate: '2023-03-31',
        currentDate: '2023-03-01',
        year: '2023',
        candidateId: 'EMP026',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Frank Miller',
        workLocation: 'Austin',
        isActive: true,
      },
      {
        name: 'Chris Wilson',
        candidateName: 'Chris Wilson',
        candidateAddress: '147 Startup Lane, Boston, USA',
        position: 'QA Engineer',
        jobRole: 'Quality Assurance Specialist',
        salary: '70000',
        basicSalary: '50000',
        basicMonthly: '4167',
        hra: '10000',
        hraMonthly: '833',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '3500',
        lta: '7000',
        otherBenefits: '1200',
        otherMonthly: '100',
        totalSalary: '70000',
        totalMonthly: '5833',
        joiningDate: '2023-05-01',
        offerExpiryDate: '2023-04-15',
        currentDate: '2023-04-01',
        year: '2023',
        candidateId: 'EMP027',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Grace Lee',
        workLocation: 'Boston',
        isActive: true,
      },
      {
        name: 'Anna Taylor',
        candidateName: 'Anna Taylor',
        candidateAddress: '258 Code Street, San Francisco, USA',
        position: 'Frontend Developer',
        jobRole: 'UI Developer',
        salary: '78000',
        basicSalary: '56000',
        basicMonthly: '4667',
        hra: '11200',
        hraMonthly: '933',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4200',
        lta: '8400',
        otherBenefits: '1600',
        otherMonthly: '133',
        totalSalary: '78000',
        totalMonthly: '6500',
        joiningDate: '2023-06-10',
        offerExpiryDate: '2023-05-25',
        currentDate: '2023-05-01',
        year: '2023',
        candidateId: 'EMP028',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Henry Adams',
        workLocation: 'San Francisco',
        isActive: true,
      },
      {
        name: 'Robert Martinez',
        candidateName: 'Robert Martinez',
        candidateAddress: '369 Backend Blvd, New York, USA',
        position: 'Backend Developer',
        jobRole: 'Server-side Engineer',
        salary: '85000',
        basicSalary: '61000',
        basicMonthly: '5083',
        hra: '12200',
        hraMonthly: '1017',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '5100',
        lta: '10200',
        otherBenefits: '2100',
        otherMonthly: '175',
        totalSalary: '85000',
        totalMonthly: '7083',
        joiningDate: '2023-07-05',
        offerExpiryDate: '2023-06-20',
        currentDate: '2023-06-01',
        year: '2023',
        candidateId: 'EMP029',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'Jane Smith',
        hrPosition: 'HR Manager',
        reportingManager: 'Ivy Chen',
        workLocation: 'New York',
        isActive: true,
      },
      {
        name: 'Lisa Anderson',
        candidateName: 'Lisa Anderson',
        candidateAddress: '741 Mobile Ave, Los Angeles, USA',
        position: 'Mobile Developer',
        jobRole: 'iOS/Android Developer',
        salary: '82000',
        basicSalary: '59000',
        basicMonthly: '4917',
        hra: '11800',
        hraMonthly: '983',
        conveyance: '19200',
        conveyanceMonthly: '1600',
        medical: '4600',
        lta: '9200',
        otherBenefits: '1900',
        otherMonthly: '158',
        totalSalary: '82000',
        totalMonthly: '6833',
        joiningDate: '2023-08-15',
        offerExpiryDate: '2023-07-31',
        currentDate: '2023-07-01',
        year: '2023',
        candidateId: 'EMP030',
        companyName: 'Tech Corp',
        companyAddress: '456 Business Ave, New York, USA',
        companyInitials: 'TC',
        companyTagline: 'Innovating the Future',
        companyMission: 'To provide cutting-edge technology solutions.',
        hrName: 'John Doe',
        hrPosition: 'HR Director',
        reportingManager: 'Jack Thompson',
        workLocation: 'Los Angeles',
        isActive: true,
      },
    ];

    for (const employee of defaultEmployees) {
      await this.create(employee);
    }
  }
}
